"""
Build the 2-page Falcon Edge AI Evidence Integrity Report.
Page 1: cover + executive summary + FCA exposure framing.
Page 2: per-finding detail table.

Reads detector JSON from /sessions/.../falcon_edge_report.json
Writes PDF to /sessions/.../mnt/Claude/Falcon_Edge_AI_Evidence_Integrity_Report.pdf
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle, PageBreak, SimpleDocTemplate, KeepTogether,
)

REPORT_JSON = Path("/sessions/compassionate-vibrant-hypatia/falcon_edge_report.json")
OUT_PDF = Path("/sessions/compassionate-vibrant-hypatia/mnt/Claude/Falcon_Edge_AI_Evidence_Integrity_Report.pdf")

# ---------- Brand palette ----------
HARDSEAL_BLUE = colors.HexColor("#0B2545")
HARDSEAL_ACCENT = colors.HexColor("#1E6091")
RISK_RED = colors.HexColor("#B22222")
RISK_AMBER = colors.HexColor("#D2691E")
RISK_GREEN = colors.HexColor("#2E7D32")
SUBTLE = colors.HexColor("#5A6675")
RULE_GREY = colors.HexColor("#C9D1D9")

# ---------- Helpers ----------
def confidence_color(c: str) -> colors.Color:
    if c in ("LIKELY_SYNTHETIC", "CONTAMINATED"):
        return RISK_RED
    if c == "PARTIALLY_CONTAMINATED":
        return RISK_AMBER
    return RISK_GREEN


def confidence_label(c: str) -> str:
    return {
        "LIKELY_SYNTHETIC": "LIKELY SYNTHETIC",
        "CONTAMINATED": "CONTAMINATED",
        "PARTIALLY_CONTAMINATED": "PARTIALLY CONTAMINATED",
        "CLEAN": "CLEAN",
    }.get(c, c)


HEURISTIC_PLAIN = {
    "MappingDensity":
        "Citation-density anomaly. Narrative cites many NIST control IDs "
        "but names few real mechanisms. Pattern of LLM padding.",
    "TimestampRegularity":
        "Synthetic-clock pattern. Audit timestamps sit on round seconds at "
        "fixed intervals. Real telemetry is Poisson-distributed.",
    "BoilerplateCluster":
        "Cross-narrative shingling. Same template paragraph reused across "
        "controls that should describe distinct mechanisms.",
    "PromptLeakage":
        "LLM residue. Phrases like 'As an AI language model' or "
        "'[INSERT X HERE]' surfaced in a final-form artifact.",
    "SentenceStructureAnomaly":
        "Flatness signal. Sentence-length variance below human-prose floor.",
    "ArtifactSpecificityIndex":
        "Grounding ratio. Tools named without versions, tenants, hashes, "
        "or owner names. Reads written, not lived.",
    "CitationGraph":
        "Document graph anomaly. Orphaned references or shallow citation "
        "depth indicate synthesized cross-references.",
}

CONTROL_TO_FAMILY = {
    "ssp_3_1_1_access_control": ("AC.L2-3.1.1", "Access Control"),
    "au_3_3_1_audit_logging": ("AU.L2-3.3.1", "Audit & Accountability"),
    "poam_batch_2026Q1": ("POA&M (multi-family)", "Cross-cutting"),
}


def business_impact(heuristic: str, artifact_id: str) -> str:
    family = CONTROL_TO_FAMILY.get(artifact_id, ("--", "--"))[0]
    if heuristic == "MappingDensity":
        return (
            f"A C3PAO assessor reading {family} will see citation padding and "
            "challenge whether the named mechanisms are actually deployed. "
            "Likely outcome: NOT MET on this objective and an interview escalation."
        )
    if heuristic == "TimestampRegularity":
        return (
            "A C3PAO will request the raw SIEM export. The uniform 5-minute "
            "cadence cannot exist in production telemetry. Audit logging "
            "evidence will be rejected and the assessor will pivot to integrity "
            "concerns across the entire AU family."
        )
    if heuristic == "BoilerplateCluster":
        return (
            "Identical implementation language across distinct controls invites "
            "the assessor to treat the entire SSP as templated rather than "
            "operational. Multi-control rejection risk."
        )
    if heuristic == "PromptLeakage":
        return (
            "Direct evidence the artifact was generated by an LLM and submitted "
            "without human review. C3PAO will treat the entire packet as "
            "untrusted. False Claims Act exposure if submitted in a contractual "
            "compliance attestation."
        )
    if heuristic == "ArtifactSpecificityIndex":
        return (
            "Without versions, tenants, owners, and hashes, the artifact cannot "
            "be re-verified. Assessor will require live system walkthrough — "
            "a longer, more expensive engagement with higher fail risk."
        )
    if heuristic == "SentenceStructureAnomaly":
        return (
            "Stylistic AI fingerprint. By itself a soft signal, but combined "
            "with other findings supports a finding of non-attestable narrative."
        )
    return (
        "Assessor will flag the artifact for additional verification. "
        "Engagement cost and timeline increase."
    )


# ---------- Build ----------
def main() -> int:
    data = json.loads(REPORT_JSON.read_text())
    packet = data["packet"]
    per_artifact = data["per_artifact"]

    OUT_PDF.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(OUT_PDF),
        pagesize=LETTER,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
        title="Falcon Edge Systems — AI Evidence Integrity Report",
        author="Hardseal",
    )

    base = getSampleStyleSheet()
    s_brand = ParagraphStyle(
        "Brand", parent=base["Normal"], fontName="Helvetica-Bold",
        fontSize=10, textColor=HARDSEAL_ACCENT, spaceAfter=2,
    )
    s_title = ParagraphStyle(
        "Title", parent=base["Title"], fontSize=22, leading=26,
        textColor=HARDSEAL_BLUE, spaceAfter=4, alignment=0,
    )
    s_subtitle = ParagraphStyle(
        "Subtitle", parent=base["Normal"], fontSize=11, leading=14,
        textColor=SUBTLE, spaceAfter=14,
    )
    s_h2 = ParagraphStyle(
        "H2", parent=base["Heading2"], fontSize=12, leading=15,
        textColor=HARDSEAL_BLUE, spaceBefore=8, spaceAfter=4,
    )
    s_body = ParagraphStyle(
        "Body", parent=base["Normal"], fontSize=10, leading=13.5,
        spaceAfter=6,
    )
    s_small = ParagraphStyle(
        "Small", parent=base["Normal"], fontSize=8, leading=10.5,
        textColor=SUBTLE,
    )
    s_table_h = ParagraphStyle(
        "TableHead", parent=base["Normal"], fontSize=8.5, leading=10,
        textColor=colors.white, fontName="Helvetica-Bold",
    )
    s_table_cell = ParagraphStyle(
        "TableCell", parent=base["Normal"], fontSize=8.5, leading=11,
    )
    s_verdict_label = ParagraphStyle(
        "VL", parent=base["Normal"], fontSize=9, leading=11,
        textColor=colors.white, fontName="Helvetica-Bold",
    )
    s_verdict_value = ParagraphStyle(
        "VV", parent=base["Normal"], fontSize=20, leading=24,
        textColor=colors.white, fontName="Helvetica-Bold",
    )

    story = []
    today = datetime.now().strftime("%B %d, %Y")

    # ---------------- PAGE 1 — COVER ----------------
    story.append(Paragraph("HARDSEAL  /  AI EVIDENCE INTEGRITY REPORT", s_brand))
    story.append(Paragraph("Falcon Edge Systems", s_title))
    story.append(Paragraph(
        f"CMMC Level 2 Readiness Pack. Q1 2026 sample. "
        f"Prepared {today}.",
        s_subtitle,
    ))

    # Verdict block
    verdict_color = confidence_color(packet["confidence"])
    verdict_label = confidence_label(packet["confidence"])
    score_pct = int(round(packet["aggregate_score"] * 100))
    artifact_count = len(per_artifact)
    flagged = sum(
        1 for r in per_artifact.values()
        if r["confidence"] in ("CONTAMINATED", "LIKELY_SYNTHETIC")
    )

    verdict_tbl = Table(
        [[
            Paragraph("OVERALL VERDICT", s_verdict_label),
            Paragraph("AGGREGATE SCORE", s_verdict_label),
            Paragraph("ARTIFACTS FLAGGED", s_verdict_label),
        ], [
            Paragraph(verdict_label, s_verdict_value),
            Paragraph(f"{packet['aggregate_score']:.2f} / 1.00 &nbsp; ({score_pct}%)", s_verdict_value),
            Paragraph(f"{flagged} of {artifact_count}", s_verdict_value),
        ]],
        colWidths=[2.4 * inch, 2.4 * inch, 2.3 * inch],
        rowHeights=[0.25 * inch, 0.55 * inch],
    )
    verdict_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), verdict_color),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(verdict_tbl)
    story.append(Spacer(1, 14))

    # Executive Summary
    story.append(Paragraph("Executive Summary", s_h2))
    story.append(Paragraph(
        "Hardseal&rsquo;s AI Provenance Detector analyzed three artifacts from the "
        "Falcon Edge Systems CMMC Level 2 readiness packet: a System Security "
        "Plan narrative for AC.L2-3.1.1, an audit logging narrative for "
        "AU.L2-3.3.1, and a four-entry POA&amp;M batch covering IA, SC, SI, "
        "and AT families. Two of three artifacts triggered hard contamination "
        "signals. The packet aggregate classifies as <b>LIKELY SYNTHETIC</b> "
        f"at score {packet['aggregate_score']:.2f}.",
        s_body,
    ))
    story.append(Paragraph(
        "The strongest signals are <b>citation-density inversion</b> "
        "(narratives cite 17 to 18 NIST control IDs while naming zero to four "
        "actual mechanisms) and <b>synthetic-clock telemetry</b> (a "
        "&ldquo;quarterly threat hunt&rdquo; sample log shows authentication events "
        "spaced exactly 300 seconds apart, on the second, with zero variance, "
        "a pattern that cannot occur in production). A factual hallucination "
        "(Azure AD Conditional Access on AWS GovCloud workloads) was also "
        "introduced into the access control narrative. These are fingerprints "
        "of LLM-generated evidence, not the artifacts of a working program.",
        s_body,
    ))

    # FCA exposure framing
    story.append(Paragraph("False Claims Act Exposure", s_h2))
    story.append(Paragraph(
        "DoJ Civil Cyber-Fraud Initiative settlements exceeded "
        "<b>$52M across nine cybersecurity-related FCA cases</b> in FY2025, "
        "driven largely by misstatements in SSPs and POA&amp;Ms submitted "
        "under DFARS 252.204-7012 and 7019/7020. Effective <b>November 10, 2026</b>, "
        "DFARS 252.204-7021 makes a CMMC Level 2 self-assessment or C3PAO "
        "assessment a condition of contract award. That turns every false "
        "narrative or fabricated evidence point into a potential FCA "
        "predicate. Submitting AI-fabricated implementation language under "
        "an officer attestation is the highest-velocity FCA exposure path "
        "Falcon Edge currently carries.",
        s_body,
    ))

    story.append(Paragraph("What This Means", s_h2))
    story.append(Paragraph(
        "A C3PAO assessor running a basic provenance check, or a relator "
        "lawyer running one for a qui tam filing, will reach the same "
        "verdict reached above in under four hours. Hardseal&rsquo;s recommendation "
        "is to remediate the flagged artifacts before the next assessor "
        "engagement, not after. Detail and remediation paths follow on Page 2.",
        s_body,
    ))

    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Methodology: Hardseal AIProvenanceDetector v0.2. Seven "
        "stdlib-only heuristics (sentence-structure anomaly, boilerplate "
        "clustering, timestamp regularity, mapping density, citation graph, "
        "prompt leakage, artifact specificity index). Deterministic, "
        "auditable, zero external dependencies.",
        s_small,
    ))

    story.append(PageBreak())

    # ---------------- PAGE 2 — DETAIL ----------------
    story.append(Paragraph("HARDSEAL  /  PER-FINDING DETAIL", s_brand))
    story.append(Paragraph("Finding Fingerprints", s_title))
    story.append(Paragraph(
        "Heuristic-by-heuristic detail for every signal at score 0.50 or above. "
        "Per-finding business impact is mapped to the affected control family.",
        s_subtitle,
    ))

    # Build finding rows
    rows = [[
        Paragraph("HEURISTIC / WHAT IT DETECTS", s_table_h),
        Paragraph("ARTIFACT &amp; CONTROL", s_table_h),
        Paragraph("SCORE", s_table_h),
        Paragraph("EVIDENCE / BUSINESS IMPACT", s_table_h),
    ]]

    seen_signatures = set()
    flagged_findings = []
    for aid, rep in per_artifact.items():
        for f in rep["findings"]:
            if f["score"] >= 0.5:
                sig = (f["heuristic"], aid, round(f["score"], 2))
                if sig in seen_signatures:
                    continue
                seen_signatures.add(sig)
                flagged_findings.append((aid, f))

    # Stable order
    flagged_findings.sort(key=lambda x: (-x[1]["score"], x[0]))

    for aid, f in flagged_findings:
        family_id, family_name = CONTROL_TO_FAMILY.get(aid, (aid, "--"))
        plain = HEURISTIC_PLAIN.get(f["heuristic"], "")
        impact = business_impact(f["heuristic"], aid)
        evidence_short = f["evidence"][:240]

        rows.append([
            Paragraph(
                f"<b>{f['heuristic']}</b><br/>"
                f"<font size=8 color='#5A6675'>{plain}</font>",
                s_table_cell,
            ),
            Paragraph(
                f"<b>{family_id}</b><br/>"
                f"<font size=8 color='#5A6675'>{family_name}<br/>"
                f"{aid}</font>",
                s_table_cell,
            ),
            Paragraph(
                f"<font color='{RISK_RED.hexval()[0:7]}'><b>{f['score']:.2f}</b></font>",
                s_table_cell,
            ),
            Paragraph(
                f"<font size=7.5 color='#5A6675'>EVIDENCE: {evidence_short}</font><br/>"
                f"<br/><b>IMPACT:</b> {impact}",
                s_table_cell,
            ),
        ])

    finding_tbl = Table(
        rows,
        colWidths=[1.7 * inch, 1.3 * inch, 0.5 * inch, 3.6 * inch],
        repeatRows=1,
    )
    finding_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HARDSEAL_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (2, 1), (2, -1), "CENTER"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, RULE_GREY),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
    ]))
    story.append(finding_tbl)

    story.append(Spacer(1, 12))
    story.append(Paragraph("Recommended Remediation Path", s_h2))
    remediation_items = [
        ("AU.L2-3.3.1, Audit Logging",
         "Replace the synthetic timestamp sample with a redacted Splunk export "
         "from the actual production index. Include source host, eventid, and "
         "millisecond resolution. If the quarterly threat hunt did not run, "
         "say so and open a POA&amp;M; do not fabricate a sample."),
        ("Multi-family POA&amp;M batch",
         "Replace the templated &ldquo;control is implemented through a combination "
         "of policy, procedure, and technical configuration&rdquo; opener with the "
         "specific tool, owner, ticket ID, and target date for each finding. "
         "Each entry should read distinctly because each gap is distinct."),
        ("AC.L2-3.1.1, Access Control",
         "Remove the &ldquo;Azure AD Conditional Access on AWS GovCloud&rdquo; "
         "language. This is a factual hallucination. Document the actual "
         "access enforcement mechanism on AWS GovCloud (IAM policies, SCPs, "
         "or whatever Falcon Edge actually deploys) with policy commit hashes "
         "and the responsible engineer."),
    ]
    for title, body in remediation_items:
        story.append(Paragraph(
            f"<b>{title}.</b> {body}",
            ParagraphStyle("Rem", parent=s_body, leftIndent=10, spaceAfter=4),
        ))

    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Hardseal &middot; Trust infrastructure for AI-era defense compliance "
        "&middot; rico@hardseal.ai &middot; hardseal.ai",
        s_small,
    ))
    # Final sweep: ensure no em dashes leaked through any auto-generated string.

    doc.build(story)
    print(f"PDF written: {OUT_PDF}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
